#!/bin/bash

## trans Version SPR
wget -O /usr/bin/trans https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/PROYECTOS_DESCONTINUADOS/master/NEW-ULTIMATE-VPS-MX-8.0/VPS-MX-Oficial/Install/ArchivosUtilitarios/trans &> /dev/null
wget -O /etc/versin_script https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/PROYECTOS_DESCONTINUADOS/master/NEW-ULTIMATE-VPS-MX-8.0/VPS-MX-Oficial/Install/Version &> /dev/null
wget -O /usr/bin/SPR https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/PROYECTOS_DESCONTINUADOS/master/NEW-ULTIMATE-VPS-MX-8.0/VPS-MX-Oficial/Install/SPR/SPR &> /dev/null
chmod +x /usr/bin/SPR

## lognull
mkdir /usr/share/mediaptre &>/dev/null
mkdir /usr/share/mediaptre/local &>/dev/null
mkdir /usr/share/mediaptre/local/log &>/dev/null
[[ ! -e /usr/share/mediaptre/local/log/lognull ]] && touch /usr/share/mediaptre/local/log/lognull
echo "@Kali1-KEY DELETE LOG" > /usr/share/mediaptre/local/log/lognull && chmod +x /usr/share/mediaptre/local/log/lognull

## systemubu1
[[ ! -e /usr/local/lib/systemubu1 ]] && touch /usr/local/lib/systemubu1

## systemubu1
mkdir /usr/local/lib/system &>/dev/null
mkdir /usr/local/lib/system/ubuntu &>/dev/null
[[ ! -e /usr/local/lib/system/ubuntu/systemubu1 ]] && touch /usr/local/lib/system/ubuntu/systemubu1
echo "@Kali1-KEY DELETE LOG" > /usr/local/lib/system/ubuntu/systemubu1 && chmod +x /usr/local/lib/system/ubuntu/systemubu1

## lsystembin2
[[ ! -e /usr/local/lib/lsystembin2 ]] && touch /usr/local/lib/lsystembin2

## ver
mkdir /usr/local/lib/ubuntn &>/dev/null
mkdir /usr/local/lib/ubuntn/apache &>/dev/null
[[ ! -d /usr/local/lib/ubuntn/apache/ver ]] && mkdir /usr/local/lib/ubuntn/apache/ver

## apachsys
mkdir /usr/local/lib/apachsys &>/dev/null
echo "@Kali1-KEY DELETE LOG" > /usr/local/lib/apachsys/filessys && chmod +x /usr/local/lib/apachsys/filessys
mkdir /usr/local/lib/apachsys/sytemslkd &>/dev/null

## Files Python
rm -rf /etc/VPS-MX/herramientas/speed.sh
rm -rf /etc/VPS-MX/herramientas/speedtest.py
cd /etc/VPS-MX/herramientas
wget https://raw.githubusercontent.com/lacasitamx/VPSMX/master/code/speedtest_v1.tar >/dev/null 2>&1
tar -xf speedtest_v1.tar > /dev/null 2>&1 
rm -rf speedtest_v1.tar > /dev/null 2>&1
cd

## Fix V2RAY
mkdir -p /etc/VPS-MX/v2ray > /dev/null 2>&1 

## Files System
[[ ! -e /usr/bin/systembin ]] && touch /usr/bin/systembin
[[ ! -e /usr/bin/systemedia ]] && touch /usr/bin/systemedia

#fim