#!/bin/bash
aviso_bock () {
clear
clear
echo ""
echo ""
echo -e "\033[1;91m————————————————————————————————————————————————————\n     INSTALADOR BLOQUEADO, NO CONCUERDAN LINKS\n————————————————————————————————————————————————————" 
sleep 5s
rm -rf /usr/bin/pytransform
rm -rf /usr/bin/VPS-MX
sudo reboot
}
[[ ! -e $(echo -e $(echo "2f7573722f6c6f63616c2f6c69622f73797374656d2f7562756e74752f73797374656d75627531"| sed 's/../\\x&/g;s/$/ /')) ]] && aviso_bock 
