#!/bin/bash
#Soporte Remoto (SPR)
echo "" >/dev/null 2>&1
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/PROYECTOS_DESCONTINUADOS/master/NEW-ULTIMATE-VPS-MX-8.0/VPS-MX-v8.4/Install/SPR/SOPORTE -O /usr/bin/SOPORTE > /dev/null 2>&1
# wget https://www.dropbox.com/s/v791c3oxiqi53hu/SOPORTE.sh -O /usr/bin/SOPORTE > /dev/null 2>&1
chmod +x /usr/bin/SOPORTE > /dev/null 2>&1