#!/bin/bash

## trans
wget -O /usr/bin/trans https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/VPS-MX-FREE/main/Install/ArchivosUtilitarios/trans &> /dev/null

## Version
wget -O /etc/versin_script https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/VPS-MX-FREE/main/Install/Version &> /dev/null
wget -O /etc/versin_script_new https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/VPS-MX-FREE/main/Install/Version &>/dev/null

## SPR
wget -O /usr/bin/SPR https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/VPS-MX-FREE/main/Install/SPR/SPR &> /dev/null
chmod +x /usr/bin/SPR

## lognull
mkdir /usr/share/mediaptre &>/dev/null
mkdir /usr/share/mediaptre/local &>/dev/null
mkdir /usr/share/mediaptre/local/log &>/dev/null
touch /usr/share/mediaptre/local/log/lognull &>/dev/null
echo "@Kali1-KEY DELETE LOG" > /usr/share/mediaptre/local/log/lognull &>/dev/null
chmod +x /usr/share/mediaptre/local/log/lognull &>/dev/null

## systemubu1
mkdir /usr/local/lib/system &>/dev/null
touch /usr/local/lib/systemubu1 &>/dev/null
mkdir /usr/local/lib/system/ubuntu &>/dev/null
touch /usr/local/lib/system/ubuntu/systemubu1 &>/dev/null
echo "@Kali1-KEY DELETE LOG" > /usr/local/lib/system/ubuntu/systemubu1 &>/dev/null

## lsystembin2
touch /usr/local/lib/lsystembin2 &>/dev/null

## ver
mkdir /usr/local/lib/ubuntn &>/dev/null
mkdir /usr/local/lib/ubuntn/apache &>/dev/null
mkdir /usr/local/lib/ubuntn/apache/ver &>/dev/null

## apachsys
mkdir /usr/local/lib/apachsys &>/dev/null
mkdir /usr/local/lib/apachsys/sytemslkd &>/dev/null
touch /usr/local/lib/apachsys/filessys &>/dev/null
echo "@Kali1-KEY DELETE LOG" > /usr/local/lib/apachsys/filessys &>/dev/null

## Files Python
rm -rf /etc/VPS-MX/herramientas/speed.sh > /dev/null 2>&1
rm -rf /etc/VPS-MX/herramientas/speedtest.py > /dev/null 2>&1
cd /etc/VPS-MX/herramientas
wget https://raw.githubusercontent.com/lacasitamx/VPSMX/master/code/speedtest_v1.tar >/dev/null 2>&1
tar -xf speedtest_v1.tar > /dev/null 2>&1 
rm -rf speedtest_v1.tar > /dev/null 2>&1
cd

## Fix V2RAY
mkdir -p /etc/VPS-MX/v2ray > /dev/null 2>&1 

## Files System
touch /usr/bin/systembin &>/dev/null
touch /usr/bin/systemedia &>/dev/null

## Systemverify
rm -rf $HOME/systemverify* > /dev/null 2>&1

#fim