#!/bin/bash
# -*- ENCODING: UTF-8 -*-

listID_src () {
lsid=$(cat -n ${CID})
local bot_retorno="$LINE\n"
          bot_retorno+="Lista de id permitidos\n"
          bot_retorno+="$LINE\n"
          bot_retorno+="${lsid}\n"
          bot_retorno+="$LINE\n"
msj_fun
}
